# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/nao/git/marsyas/src/marsyas_max-msp/CMakeLists.txt))

/Users/nao/git/marsyas/build5/CMakeFiles/cmake.check_cache: $(TARGETS)
	/Applications/CMake.app/Contents/bin/cmake -H/Users/nao/git/marsyas -B/Users/nao/git/marsyas/build5
